name: build docker container

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter-repo2docker
    - name: build repository
      run: |
        jupyter-repo2docker --image-name repo-container --no-run $GITHUB_WORKSPACE
        docker exec -it repo-container \
          jupyter nbconvert --to notebook \
          --ExecutePreprocessor.kernel_name=julia-1.4 --ExecutePreprocessor.timeout=600 \
          --execute notebooks/conditional-power-and-friends.ipynb 
