name: build and push docker container

on:
  push:
    branches: 
    - 'master'
    paths: 
    - '.binder/**'
  pull_request:
    branches: 
    - 'master'
    paths: 
    - '.binder/**'

env:
  INPUT_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/unplanned-sample-size-adaptation
      
jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: local repo2docker  
      uses: machine-learning-apps/repo2docker-action@0.2 
      with: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NO_PUSH: true 
    - name: start and test container
      run: |
        docker run -d --name container ${INPUT_IMAGE_NAME}
        docker exec container ./run
  push-image:
    runs-on: ubuntu-latest
    needs: build-and-test-image
    steps:
      - name: push image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${INPUT_IMAGE_NAME}:latest
