name: build container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  repo2docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo2docker Action
      uses: machine-learning-apps/repo2docker-action@0.2
