name: build and push docker container

on:
  push:
    branches: [ master ]
    paths: [ .binder ]
  pull_request:
    branches: [ master ]
    paths: [ .binder ]
    
jobs:
  repo2docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo2docker Action  
      with: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      uses: machine-learning-apps/repo2docker-action@0.2
