name: build and push docker container

on:
  push:
    branches: [ master ]
    paths: [ .binder ]
  pull_request:
    branches: [ master ]
    paths: [ .binder ]
    
jobs:
  repo2docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo2docker Action  
      with: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        MYBINDERORG_TAG: ${{ github.event.ref }}      
      uses: machine-learning-apps/repo2docker-action@0.2 
    - name: start container
      run: |
        docker run -d --name repo-container ${{ secrets.DOCKER_USERNAME }}/unplanned-sample-size-adaptation
    - name: execute jupyter notebook
      run: |
        docker exec repo-container \
          jupyter nbconvert --to notebook \
          --ExecutePreprocessor.kernel_name=julia-1.4 --ExecutePreprocessor.timeout=600 \
          --execute notebooks/conditional-power-and-friends.ipynb 
