name: build container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  repo2docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: repo2docker Action  
      with: 
        INPUT_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        INPUT_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $INPUT_DOCKER_USERNAME
      uses: machine-learning-apps/repo2docker-action@0.2
