name: run

on: 
  pull_request:
    branches: 'master'
    paths-ignore: '.binder/**' 
  push:
    branches: 'master'
    paths-ignore: '.binder/**'

jobs:
  execute-run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker run -d --name container ${{ secrets.DOCKER_USERNAME }}/unplanned-sample-size-adaptation
        docker exec container ./run
