name: run

on:
  push:
  pull_request:

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository 
      uses: actions/checkout@v2
    - name: setup R
      uses: r-lib/actions/setup-r@master
    - name: cache renv packages
      uses: actions/cache@v1
      with:
        path: $HOME/.local/share/renv
        key: r-${{ hashFiles('renv.lock') }}
        restore-keys: r-
    - name: install packages
      run: |
        sudo apt-get install libcurl4-openssl-dev
        R -e 'install.packages("renv")'
        R -e 'renv::restore()'
    - run: ./run
